### In this file, I have built classifier models, 1 is Naive Bayesian and the other is Vanilla Neural Network classifier. The dataset used is titanic dataset.

In [89]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import KNNImputer
import polars as pl

* Polars is also being used as it has the ability to read data types accurately in scenerios where pandas sometimes breaks down.


* So the normal workflow for me is to load the dataset with polars and then convert to pandas. It reduces chances of error.

In [90]:
df= sns.load_dataset('titanic')
df_polars= pl.from_pandas(df)

Here is an important hack:
* If you are working with excel files, they are very fussy in terms of the inconsistency in datatypes when loading the file etc.
* The hack is to convert the excel files to csv with `df.to_csv()` function and then work on that csv file
* This makes life easier as the errors don't occur with .csv.

In [91]:
df_polars.dtypes

[Int64,
 Int64,
 String,
 Float64,
 Int64,
 Int64,
 Float64,
 String,
 Categorical(ordering='physical'),
 String,
 Boolean,
 Categorical(ordering='physical'),
 String,
 String,
 Boolean]

In [92]:
df.to_csv('Titanic_Dataset.csv', )

In [93]:
df= pd.read_csv('Titanic_Dataset.csv', index_col=False)

## Ordinal Encoding to handle missing as well as for Classification

In [94]:
oencoder= OrdinalEncoder()
encoded= oencoder.fit_transform(df)

In [95]:
df=pd.DataFrame(data=encoded, columns= df.columns)

In [96]:
df

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,0.0,2.0,1.0,28.0,1.0,0.0,18.0,2.0,2.0,1.0,1.0,NaN,2.0,0.0,0.0
1,1.0,1.0,0.0,0.0,51.0,1.0,0.0,207.0,0.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
2,2.0,1.0,2.0,0.0,34.0,0.0,0.0,41.0,2.0,2.0,2.0,0.0,NaN,2.0,1.0,1.0
3,3.0,1.0,0.0,0.0,47.0,1.0,0.0,189.0,2.0,0.0,2.0,0.0,2.0,2.0,1.0,0.0
4,4.0,0.0,2.0,1.0,47.0,0.0,0.0,43.0,2.0,2.0,1.0,1.0,NaN,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886.0,0.0,1.0,1.0,35.0,0.0,0.0,85.0,2.0,1.0,1.0,1.0,NaN,2.0,0.0,1.0
887,887.0,1.0,0.0,0.0,24.0,0.0,0.0,153.0,2.0,0.0,2.0,0.0,1.0,2.0,1.0,1.0
888,888.0,0.0,2.0,0.0,NaN,1.0,2.0,131.0,2.0,2.0,2.0,0.0,NaN,2.0,0.0,0.0
889,889.0,1.0,0.0,1.0,34.0,0.0,0.0,153.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0
890,890.0,0.0,2.0,1.0,42.0,0.0,0.0,30.0,1.0,2.0,1.0,1.0,NaN,1.0,0.0,1.0

In [97]:
df.isna().sum()

Unnamed: 0       0
survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [98]:
imputer= KNNImputer()
imputed_data= imputer.fit_transform(df)

In [99]:
imputed_data

array([[  0.,   0.,   2., ...,   2.,   0.,   0.],
       [  1.,   1.,   0., ...,   0.,   1.,   0.],
       [  2.,   1.,   2., ...,   2.,   1.,   1.],
       ...,
       [888.,   0.,   2., ...,   2.,   0.,   0.],
       [889.,   1.,   0., ...,   0.,   1.,   1.],
       [890.,   0.,   2., ...,   1.,   0.,   1.]])

In [100]:
imputed_data= pd.DataFrame(data= imputed_data, columns= df.columns)

In [101]:
imputed_data

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,0.0,2.0,1.0,28.0,1.0,0.0,18.0,2.0,2.0,1.0,1.0,4.2,2.0,0.0,0.0
1,1.0,1.0,0.0,0.0,51.0,1.0,0.0,207.0,0.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
2,2.0,1.0,2.0,0.0,34.0,0.0,0.0,41.0,2.0,2.0,2.0,0.0,4.2,2.0,1.0,1.0
3,3.0,1.0,0.0,0.0,47.0,1.0,0.0,189.0,2.0,0.0,2.0,0.0,2.0,2.0,1.0,0.0
4,4.0,0.0,2.0,1.0,47.0,0.0,0.0,43.0,2.0,2.0,1.0,1.0,4.2,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886.0,0.0,1.0,1.0,35.0,0.0,0.0,85.0,2.0,1.0,1.0,1.0,2.8,2.0,0.0,1.0
887,887.0,1.0,0.0,0.0,24.0,0.0,0.0,153.0,2.0,0.0,2.0,0.0,1.0,2.0,1.0,1.0
888,888.0,0.0,2.0,0.0,35.8,1.0,2.0,131.0,2.0,2.0,2.0,0.0,2.4,2.0,0.0,0.0
889,889.0,1.0,0.0,1.0,34.0,0.0,0.0,153.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0
890,890.0,0.0,2.0,1.0,42.0,0.0,0.0,30.0,1.0,2.0,1.0,1.0,1.8,1.0,0.0,1.0

In [102]:
imputed_data.isna().sum()

Unnamed: 0     0
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

# Gaussian Naive Bayes Classifier

In [103]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

nb_classifier= GaussianNB()

X= imputed_data.drop('survived', axis=1)
Y= imputed_data['survived']
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size= 0.2, random_state=42)


nothing =nb_classifier.fit(X_train, Y_train)
predictions= nb_classifier.predict(X_test)


accuracy= accuracy_score(predictions, Y_test)
print("Accuracy of the model is: ", accuracy)

Accuracy of the model is:  1.0

# Neural Network Classifier

For Neural Network, we will also scale the dataset.

In [104]:
from sklearn.preprocessing import MinMaxScaler

# scaler= MinMaxScaler()
# scaled_dataset= scaler.fit_transform(imputed_data)
scaled_dataset= imputed_data

In [105]:
dataset= pd.DataFrame(data= scaled_dataset, columns=imputed_data.columns)
dataset['survived']=dataset['survived'].astype(int)

X=dataset.drop('survived', axis=1)
Y=dataset['survived']

X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size= 0.1, random_state=42)


dataset

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0.0,0,2.0,1.0,28.0,1.0,0.0,18.0,2.0,2.0,1.0,1.0,4.2,2.0,0.0,0.0
1,1.0,1,0.0,0.0,51.0,1.0,0.0,207.0,0.0,0.0,2.0,0.0,2.0,0.0,1.0,0.0
2,2.0,1,2.0,0.0,34.0,0.0,0.0,41.0,2.0,2.0,2.0,0.0,4.2,2.0,1.0,1.0
3,3.0,1,0.0,0.0,47.0,1.0,0.0,189.0,2.0,0.0,2.0,0.0,2.0,2.0,1.0,0.0
4,4.0,0,2.0,1.0,47.0,0.0,0.0,43.0,2.0,2.0,1.0,1.0,4.2,2.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886.0,0,1.0,1.0,35.0,0.0,0.0,85.0,2.0,1.0,1.0,1.0,2.8,2.0,0.0,1.0
887,887.0,1,0.0,0.0,24.0,0.0,0.0,153.0,2.0,0.0,2.0,0.0,1.0,2.0,1.0,1.0
888,888.0,0,2.0,0.0,35.8,1.0,2.0,131.0,2.0,2.0,2.0,0.0,2.4,2.0,0.0,0.0
889,889.0,1,0.0,1.0,34.0,0.0,0.0,153.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0
890,890.0,0,2.0,1.0,42.0,0.0,0.0,30.0,1.0,2.0,1.0,1.0,1.8,1.0,0.0,1.0

In [106]:
print(f"Size of X_train: {X_train.shape}")
print(f"Size of X_test: {X_test.shape}")
print(f"Size of Y_train: {Y_train.shape}")
print(f"Size of Y_test: {Y_test.shape}")

Size of X_train: (801, 15)
Size of X_test: (90, 15)
Size of Y_train: (801,)
Size of Y_test: (90,)

In [108]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout


model = Sequential([
    Dense(128, input_shape=(X_train.shape[1],), activation='relu'),  # Input layer with 16 units
      
    Dense(64, activation='relu'),  
    Dense(1, activation='sigmoid')  ])


model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy', 'recall', 'precision'])

model.fit(X_train, Y_train, epochs=50, batch_size=30)

predicted=model.predict(X_test)
predicted = (predicted > 0.5).astype(int)


accuracy= accuracy_score(Y_test, predicted)
print('The accuracy is: ', accuracy)

C:\Users\PMLS\OneDrive - Higher Education Commission\Documents\University Work\FYP\Feasibility Study\feasibility\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 5s 12ms/step - accuracy: 0.5550 - loss: 3.5950 - precision: 0.4260 - recall: 0.4440
Epoch 2/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6010 - loss: 1.0692 - precision: 0.4612 - recall: 0.4845
Epoch 3/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6094 - loss: 1.1198 - precision: 0.4990 - recall: 0.5391
Epoch 4/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6570 - loss: 0.9923 - precision: 0.6006 - recall: 0.4843
Epoch 5/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6768 - loss: 0.6943 - precision: 0.5901 - recall: 0.6105
Epoch 6/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7772 - loss: 0.5305 - precision: 0.7567 - recall: 0.6099
Epoch 7/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7828 - loss: 0.4901 - precision: 0.7422 - recall: 0.6945
Epoch 8/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7741 - loss: 0.6265 - precision: 0.6984 - recall: 0.6431
Epoch 9/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7444 - loss: 0.5118 - precision: 0.6505 - recall: 0.6600
Epoch 10/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7250 - loss: 0.6928 - precision: 0.6735 - recall: 0.5727
Epoch 11/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8629 - loss: 0.3578 - precision: 0.8868 - recall: 0.7496
Epoch 12/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7336 - loss: 0.6626 - precision: 0.6869 - recall: 0.5866
Epoch 13/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7096 - loss: 1.0383 - precision: 0.6349 - recall: 0.6463
Epoch 14/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7669 - loss: 0.5516 - precision: 0.6997 - recall: 0.6516
Epoch 15/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6893 - loss: 0.9997 - precision: 0.6240 - recall: 0.5716
Epoch 16/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.7594 - loss: 0.7946 - precision: 0.7309 - recall: 0.6077
Epoch 17/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8275 - loss: 0.4701 - precision: 0.7970 - recall: 0.7016
Epoch 18/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8808 - loss: 0.2784 - precision: 0.8820 - recall: 0.8007
Epoch 19/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8960 - loss: 0.2659 - precision: 0.8762 - recall: 0.8430
Epoch 20/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9368 - loss: 0.1938 - precision: 0.9496 - recall: 0.8837
Epoch 21/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - accuracy: 0.8874 - loss: 0.3153 - precision: 0.8563 - recall: 0.8586
Epoch 22/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8362 - loss: 0.3826 - precision: 0.7955 - recall: 0.7531
Epoch 23/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6941 - loss: 1.0913 - precision: 0.5966 - recall: 0.6735
Epoch 24/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7900 - loss: 0.6035 - precision: 0.7086 - recall: 0.8220
Epoch 25/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8937 - loss: 0.3029 - precision: 0.9032 - recall: 0.8172
Epoch 26/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9139 - loss: 0.2297 - precision: 0.8756 - recall: 0.9003
Epoch 27/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9349 - loss: 0.1642 - precision: 0.9197 - recall: 0.9088
Epoch 28/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9355 - loss: 0.1758 - precision: 0.9305 - recall: 0.8934
Epoch 29/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.9355 - loss: 0.1477 - precision: 0.9278 - recall: 0.9000
Epoch 30/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9112 - loss: 0.2134 - precision: 0.9057 - recall: 0.8622
Epoch 31/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9591 - loss: 0.1238 - precision: 0.9482 - recall: 0.9390
Epoch 32/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9703 - loss: 0.1216 - precision: 0.9726 - recall: 0.9492
Epoch 33/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9730 - loss: 0.1113 - precision: 0.9736 - recall: 0.9545
Epoch 34/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9829 - loss: 0.1028 - precision: 0.9921 - recall: 0.9649
Epoch 35/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9785 - loss: 0.1062 - precision: 0.9746 - recall: 0.9677
Epoch 36/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9795 - loss: 0.1035 - precision: 0.9771 - recall: 0.9669
Epoch 37/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9911 - loss: 0.0834 - precision: 0.9895 - recall: 0.9873
Epoch 38/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9698 - loss: 0.1069 - precision: 0.9750 - recall: 0.9470
Epoch 39/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9793 - loss: 0.0899 - precision: 0.9823 - recall: 0.9621
Epoch 40/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9737 - loss: 0.1074 - precision: 0.9606 - recall: 0.9719
Epoch 41/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9785 - loss: 0.1078 - precision: 0.9721 - recall: 0.9733
Epoch 42/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9842 - loss: 0.0798 - precision: 0.9833 - recall: 0.9751
Epoch 43/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9948 - loss: 0.0649 - precision: 1.0000 - recall: 0.9856
Epoch 44/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9894 - loss: 0.0635 - precision: 0.9910 - recall: 0.9802
Epoch 45/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9912 - loss: 0.0704 - precision: 0.9919 - recall: 0.9837
Epoch 46/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - accuracy: 0.9598 - loss: 0.1137 - precision: 0.9412 - recall: 0.9550
Epoch 47/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9832 - loss: 0.0747 - precision: 0.9808 - recall: 0.9755
Epoch 48/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.9296 - loss: 0.2281 - precision: 0.8919 - recall: 0.9358
Epoch 49/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9861 - loss: 0.0727 - precision: 0.9784 - recall: 0.9860
Epoch 50/50
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9946 - loss: 0.0468 - precision: 0.9920 - recall: 0.9938
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
The accuracy is:  0.9666666666666667

# Conclusion:

The performance of both the models has been good although the Neural Network lacks performance due to lack of tuning. Repeated trials can help us achieve better results.The Naive Bayesian Classifer has 100% accuracy while Vanilla Neural Network showed 96-97% accuracy with 2 layers (1st of 128 units and 2nd of 64 units). The metrics included with the model that are precision, recall, loss seem erratic at points as the model size and batch size is small.